### ISSUE TITLE
implement default values

### ISSUE THREAD

**Issue by hymie0** [nlarn/nlarn#279]
I would like to have my autopickup preferences remembered from game to game.  It would be nice if a config file could be read that might include things like
* preferred name
* preferred build
* autopickup
* other options that can be set in game, but I can't think of any off the top of my head

**Comment by jaydg** [comment]
Did you see the section "Game configuration" in the [README](https://github.com/nlarn/nlarn#game-configuration)?

The distribution contains a [sample configuration file](https://github.com/nlarn/nlarn/blob/master/nlarn.ini-sample), which when copied into the correct location and modified accordingly, can define the values you want to predefine.
