### ISSUE TITLE
Movement Keymapping Problem 

### ISSUE THREAD

**Issue by jnooner** [nlarn/nlarn#282]
When trying to use my numpad; I ran into a strange issue where the keymapping seems to not quite be interpreted correctly.

Key Pressed -- Interpreted key pressed
1 -- q
2 -- r
3 -- s
4 -- t
5 -- u
6 -- v
7 -- w
8 -- x
9 -- y

Wrote a small logging program to try and track the cause of the issue... what I found was interesting...

I put this right above 'main' in nlarn.c

void log_output_info(char data)
{
    FILE *f = fopen("log.output", "a");
    if (f == NULL)
    {
        printf("Error opening file!\n");
        exit(1);
    }

	fprintf(f, "\n");
    fprintf(f, "%i", data);

    fclose(f);
}

... and added a line:

            ch = display_getch();  // from line 206 of nlarn.c
            
            log_output_info(ch); // newly added

The output of pushing 1, 2, 3, 4, 5, 6, 7, 8, 9 on the numeric keypad this was:

27
79
113
27
79
114
27
79
115
27
79
116
27
79
117
27
79
118
27
79
119
27
79
120
27
79
121

So... it looks like hitting anything on the numeric keypad is interpreted as 3 key presses!?

Hitting "1" on the keypad produces: 
27
79
113

Which is interpreted as 'q', in-game; for some reason?  It's interpreting the last character in the set of 3?

I'll keep digging -- this is interesting.

This seems to imply that we could allocate space for 3-4 bytes for reading character information... and encode these series:  27,79,113 in hexadecimal... and conditionalize the hexadecimal value of the 'ch' variable.

Then we'd reach my goal of being able to use the keypad to move around instead of this irksome h, j, k, l, y, u, b, n.

**Comment by jnooner** [comment]
Herein lies the answer:
https://stackoverflow.com/questions/10463201/getch-and-arrow-codes

So... you could use a process like this --
			if(ch == 27)
			{
			  log_output_info_string("Escape character logged!");
			  
			  ch = getch();
			  
			  if(ch == 79)
			  {
			  	ch = getch();
			  	if(ch == 113)
			  	{
			  		log_output_info_string("Escape character logged and q!");
			  	}
			  }			  
			}

To identify exactly which escape sequence (and specifically, which numeric keypress) is in use.

I believe I almost have this solved.  I had no idea getch would behave this way prior to this.

**Comment by jnooner** [comment]
Okay... here is the full solution:

//  Add a new 'escBoolean' to nlarn.c 0 means false, 1 means true
    char run_cmd = 0;
    int ch = 0;
    gboolean adj_corr = FALSE;
    guint end_resting = 0;
    int escBoolean = 0;

To track the numeric keypress of the number 1:

        case 'q':
        {   
        	if(escBoolean == 0)
        	{
        	    sobject_t ms = map_sobject_at(game_map(nlarn, Z(nlarn->p->pos)),
                                              nlarn->p->pos);

            	if ((ms == LS_FOUNTAIN || ms == LS_DEADFOUNTAIN)
                    	&& display_get_yesno("There is a fountain here, drink from it?",
                                         NULL, NULL, NULL))
            	{
                	moves_count = player_fountain_drink(nlarn->p);
            	}
            	else
            	{
                	player_quaff(nlarn->p);
            	}
        	}
        	else
        	{
        		// #1 numeric key depressed
        		moves_count = player_move(nlarn->p, GD_SW, run_cmd == 0);
        	}

        }
        break;

Unfortunately; on my mac osx operating system; I don't really have  numlock that I can run tests with.  I realize this solution was a little ugly... but I am given to believe that more than just my operating system would have issues trying to navigate using the numeric keypad.

I would be happy to push my final solution if you would like?

I finally have the game to a state where I'm willing to actually play it; and so shall I bid you adieu.

**Comment by jnooner** [comment]
If you wish to access my changes; you can access them through the branch and url below:

branch:  jnooner_282
https://github.com/jnooner/nlarn.git

Let me know what you think.

**Comment by jaydg** [comment]
Thanks for the report, I think I have finally fixed the issue. 

I have used a totally different approach, though.

**Comment by jnooner** [comment]
Thank you for letting me know. I am taking a look at your code changes.  If
you have the issue fresh in your mind; did you foresee any issues with the
approach I took?

**Comment by jaydg** [comment]
@jnooner I tried to limit the changes; as you'll see when you look at my implementation, I used a generic input function which already exists, ensured it is used everywhere and checked there if numlock is active.
