### ISSUE TITLE
Crash: Difficulty 10, Level D5 when fighting Trolls or Vampires

### ISSUE THREAD

**Issue by r0cc0r0cc0** [nlarn/nlarn#300]
If I don't engage (hit or spell) Trolls or Vampires on this level it's all good, but as soon as I do it, the program crashes (goes away) and when I start again I'm back to where I started (on D5).
Vampire is in the closed room in the center, Troll is in the room where you start with this save file.
Thanks for help on this!
[nlarn-sav.zip](https://github.com/nlarn/nlarn/files/6353990/nlarn-sav.zip)

**Comment by jaydg** [comment]
Thanks for your bug report!

I understood the crash, it is a good old division by zero. You went where no one went before you - this crash only occurs when playing on difficulty level 10.

**Comment by r0cc0r0cc0** [comment]
Wow!  I managed to work around it and get to level 11 with some less-reproducible glitches here and there, but I can say I wouldn't have made it past level 8 without some well-timed copies of the .sav file...  :D  
So I need to update nlarn then to fix that level 10 bug?

**Comment by jaydg** [comment]
I haven't released that fix yet, I want to track down the other issue you reported first. 

As far as I know you can ask GitHub to notify you once a release is created.
